import type { Metadata } from 'next'
import localFont from 'next/font/local'

import './globals.css'

const inter = localFont({
  src: './fonts/inter-vf.ttf',
  variable: '--font-inter',
  weight: '100 200 300 400 500 600 700 800 900',
})

const grotesk = localFont({
  src: './fonts/space-grotesk-vf.ttf',
  variable: '--font-grotesk',
  weight: '300 400 500 600 700',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={`${inter.variable} ${grotesk.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
